# Generated by Django 5.0.1 on 2024-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(),
        ),
    ]
